### ISSUE TITLE
Event based workflow doesn't seem to work

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-runner#72]
When creating an event based workflow that should trigger on a specific tag it doesn't work.

Error that shows up in Vamp QuickStart when using this Vamp workflow definition:
```yaml
name: helloresponse
kind: workflow
breed:
  reference: helloresponse
schedule:
  event:
    tags:
    - archive
environment_variables: {}
scale:
  cpu: 0.1
  memory: 128.00MB
  instances: 1
network: HOST
arguments: []
```
output log:

13:57:14.580
 | ERROR | io.vamp.common.http.HttpClient           |                                          | rsp [HttpMethod(POST) http://localhost:4400/scheduler/iso8601] - unexpected status code: 400
13:57:14.584 | ERROR | io.vamp.common.http.HttpClient           |                                          | rsp [HttpMethod(POST) http://localhost:4400/scheduler/iso8601] - unexpected status code: 400
13:57:14.586 | ERROR | io.vamp.common.http.HttpClient           |                                          | rsp [HttpMethod(POST) http://localhost:4400/scheduler/iso8601] - unexpected status code: 400
13:57:14.598 | ERROR | io.vamp.common.notification.Notification |                                          | Workflow response error.
13:57:14.599 | ERROR | io.vamp.common.notification.Notification |                                          | Workflow response error.
13:57:14.600 | ERROR | io.vamp.common.notification.Notification |                                          | requirement failed: Vertex already exists in graph helloresponse
io.vamp.common.http.HttpClientException: requirement failed: Vertex already exists in graph helloresponse
	at io.vamp.common.http.HttpClient$$anonfun$httpWithEntity$1$$anonfun$apply$4.apply(HttpClient.scala:136)
	at io.vamp.common.http.HttpClient$$anonfun$httpWithEntity$1$$anonfun$apply$4.apply(HttpClient.scala:132)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Success.map(Try.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:409)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
13:57:14.607 | ERROR | io.vamp.common.notification.Notification |                                          | Workflow response error.
13:57:14.607 | ERROR | io.vamp.common.notification.Notification |                                          | requirement failed: Vertex already exists in graph helloresponse
io.vamp.common.http.HttpClientException: requirement failed: Vertex already exists in graph helloresponse
	at io.vamp.common.http.HttpClient$$anonfun$httpWithEntity$1$$anonfun$apply$4.apply(HttpClient.scala:136)
	at io.vamp.common.http.HttpClient$$anonfun$httpWithEntity$1$$anonfun$apply$4.apply(HttpClient.scala:132)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Success.map(Try.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:409)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
13:57:14.610 | ERROR | io.vamp.common.notification.Notification |                                          | requirement failed: Vertex already exists in graph helloresponse
io.vamp.common.http.HttpClientException: requirement failed: Vertex already exists in graph helloresponse
	at io.vamp.common.http.HttpClient$$anonfun$httpWithEntity$1$$anonfun$apply$4.apply(HttpClient.scala:136)
	at io.vamp.common.http.HttpClient$$anonfun$httpWithEntity$1$$anonfun$apply$4.apply(HttpClient.scala:132)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Success.map(Try.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:409)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
13:57:14.631 | ERROR | io.vamp.common.http.HttpClient           |                                          | rsp [HttpMethod(POST) http://localhost:4400/scheduler/iso8601] - unexpected status code: 400
13:57:14.633 | ERROR | io.vamp.common.notification.Notification |                                          | Workflow response error.
13:57:14.633 | ERROR | io.vamp.common.notification.Notification |                                          | requirement failed: Vertex already exists in graph helloresponse
io.vamp.common.http.HttpClientException: requirement failed: Vertex already exists in graph helloresponse
	at io.vamp.common.http.HttpClient$$anonfun$httpWithEntity$1$$anonfun$apply$4.apply(HttpClient.scala:136)
	at io.vamp.common.http.HttpClient$$anonfun$httpWithEntity$1$$anonfun$apply$4.apply(HttpClient.scala:132)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Success.map(Try.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:409)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
13:57:14.637 | ERROR | io.vamp.common.http.HttpClient           |                                          | rsp [HttpMethod(POST) http://localhost:4400/scheduler/iso8601] - unexpected status code: 400
13:57:14.637 | ERROR | io.vamp.common.notification.Notification |                                          | Workflow response error.
13:57:14.637 | ERROR | io.vamp.common.notification.Notification |                                          | requirement failed: Vertex already exists in graph helloresponse
io.vamp.common.http.HttpClientException: requirement failed: Vertex already exists in graph helloresponse
	at io.vamp.common.http.HttpClient$$anonfun$httpWithEntity$1$$anonfun$apply$4.apply(HttpClient.scala:136)
	at io.vamp.common.http.HttpClient$$anonfun$httpWithEntity$1$$anonfun$apply$4.apply(HttpClient.scala:132)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Success.map(Try.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:409)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by dragoslav** [comment]
This will be investigated/fixed as a part of https://github.com/magneticio/vamp/issues/881 (related to Vamp project/repo).
